wormholes-org/wormholes

- consensus/istanbul/ibft/core/preprepare.go
- eth/handler.go
- miner/certify.go
- miner/signatureProcess.go
- miner/worker.go
1. fix certify event bugs
2. remove istanbulcommon.ErrOldMessage
> Fix eventbugs

- internal/ethapi/api.go
> perf: modify version

- internal/ethapi/api.go
- miner/certify.go
- miner/signatureProcess.go
optimize log system, fix a problem that print too much logs
> fix: optimize log system, fix a problem that print too much logs

- params/version.go
> fix:modify the version to 0.9.5

- consensus/istanbul/ibft/engine/engine.go
> feat:Adjust the penalty ratio

- accounts/abi/bind/backends/simulated.go
- core/blockchain.go
- core/genesis.go
- core/state/statedb.go
- core/types/nfttypes.go
- eth/state_accessor.go
- internal/ethapi/api.go
- miner/worker.go
> Perf modifyipfsaddress

- consensus/istanbul/backend/engine.go
- consensus/istanbul/ibft/engine/engine.go
- core/state/statedb.go
- miner/miner.go
- miner/signatureProcess.go
- miner/worker.go
1. remove fork
2. perf empty block logic
> Feat emptyandnormalblock

- core/state/statedb.go
- core/state_transition.go
- core/tx_pool.go
- core/vm/errors.go
- core/vm/evm.go
- light/txpool.go
1. remove creator rewards when exchanging snfts
2. modify 280 to 700 when users open exchanger
> fix: modify 280 to 700

- consensus/istanbul/backend/backend.go
- consensus/istanbul/backend/handler.go
- consensus/istanbul/ibft/core/core.go
- core/evm.go
- core/vm/evm.go
- miniredis/miniredis.go
> Develop : modify royalty to default 10%

- core/types/nfttypes.go
fix: modify defaultroyalty to 1000
> fix: modify defaultroyalty to 1000

- consensus/istanbul/backend/engine.go
- core/blockchain.go
- core/types/validator_account.go
- miner/signatureProcess.go
- miner/worker.go
generate empty block with validators weight
> Perf emptyblockweight : generate empty block with validators weight

- consensus/istanbul/ibft/engine/engine.go
- core/blockchain.go
> fix : verify the difficulty of the blocks

- core/evm.go
- core/types/nfttypes.go
- core/vm/evm.go
> Perf modifysnftvote

- miner/signatureProcess.go
modify the validator coefficient when calculate the received sum of empty block
> fix: modify the validator coefficient

- miner/worker.go
- params/version.go
- wormholes_install.sh
> Fix emptylooppanic

- eth/protocols/eth/handler.go
- eth/protocols/eth/handlers.go
add some logs to print errors for handling messages.
> fix: add some logs to print errors for handling messages.

- miner/certify_test.go
- params/version.go
- wormholes_install.sh
> fix: modify the version to v0.11.2

- miner/worker.go
- params/version.go
- wormholes_install.sh
> Perf fixtime

- miner/worker.go
> fix: remove logs of empty block

- miner/worker.go
- params/version.go
- wormholes_install.sh
1. inital condition of emtpy block
2. modify version to v0.11.4
> fix: inital condition of emtpy block

- eth/handler.go
- node/defaults.go
- p2p/peer.go
- p2p/server.go
- params/version.go
- wormholes_install.sh
> Feat randomremovepeers

- core/evm.go
- core/state/statedb.go
- core/state_transition.go
- core/tx_list.go
- core/tx_pool.go
- core/types/nfttypes.go
- core/vm/evm.go
- core/vm/interface.go
- internal/ethapi/api.go
- light/txpool.go
- params/protocol_params.go
create a new transaction 28 for fored sales snfts
> Feat newtx28

- cmd/utils/flags.go
- node/config.go
- p2p/discover/common.go
- p2p/discover/lookup.go
- p2p/discover/table.go
- p2p/discover/v4_udp.go
- p2p/discover/v4wire/v4wire.go
- p2p/discover/v5_udp.go
- p2p/peer_error.go
- p2p/server.go
> Feat modifyp2pprotocol

- node/defaults.go
- p2p/server.go
> fix: cancel remove peers

- core/blockchain.go
- params/version.go
- wormholes_install.sh
perf the selection of random validators
> Perf random11 coefficient

- core/blockchain.go
- miner/worker.go
> perf:coefficients add lock
